site_name: Data Pipeline Agent
site_description: AI-powered agent for data pipeline operations with Clean Architecture, RAG, and LangGraph
site_author: Victor Cappelletto
repo_url: https://github.com/your-username/data-pipeline-agent
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to system theme
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  
  - Deployment:
      - Quick Start: deployment/quickstart.md
      - Production Deployment: deployment/production-deployment.md
      - Requirements & Context: deployment/requirements.md
  
  - Architecture:
      - Clean Architecture: architecture/clean-architecture.md
      - Agent Flow & Diagrams: architecture/agent-flow.md
  
  - Specialists:
      - Overview: specialists/overview.md
  
  - Testing:
      - Test Results: testing/test-results.md
  
  - Development:
      - Pending Improvements: development/pending-improvements.md
  
  - Examples:
      - Basic Examples: examples/basic.md
  
  - API Reference:
      - Specialists API: api/specialists.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            members_order: source
            heading_level: 2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/data-pipeline-agent
    - icon: fontawesome/solid/envelope
      link: mailto:victor.cappelletto@example.com

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/dark-mode-fix.js

copyright: Copyright &copy; 2025 TechCorp Inc - DataHub Operations Data Platform
